spring:
  profiles:
    include: security-off
  main:
    banner-mode: console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB
security:
  jwt:
    # validity time in minutes
    validity-time: 30
    secret-key: s1CXLBUbHJ/4rgyxfZZa5dechvLsYaND22sFDMQKyX0HXnpH2WowxUXVPDVKN8fnTUaejQsXQFqjKLPIGm/mN1V4SYfMMoPYZYvPg2sVjbYcnshdyHRlNOhE3ZdYyCFNk7JQ8qK+yWxeFnK+IAZ86p8M2Qec2WvsJEnc2ivBKHDMjNZs0sCvAhBFSVi4Q/OQXJbX1Zo3TioKdaNr8tLEJ/iVuRjHx9V8YUwY7HsfjQkbu7ZMvRMk+VHmiL/XcsEEo3GMeR6MGvjp1OiYqvXvRJBdUUQOIwpBao2tc2AIfsj3udi8g69J3D9qMMb3Kc4+3CtDTPeRCSIt87AjXUzCaU6Ul3kfRcHO7PoPDOEDllkzbxrTzC+O5axSevsS3P6wAvYRGJ85Wl4iHfCOHUCNAutxLp7qNDrIDHVsahl2KJkHbrrtwXimeGc/XGAspWA4mLg7J+7RkWjiAb2QZLb0eJ8Gpe9pI1hJ3YsK3bgGN5IJUW0fPN2xeYCPE+/mbsj3DEvl/CKK61Q6yG9MGunfOtUv8nQeh5lQfytAQGr6szMub3r+jaQUa4RgJZ8wSa+blooKlaycShsR5AqZ5ZLQq8btf94UCe9grHFp7wtAmFc0eX7QPJH6TizJUZvti3vhnywvxNvYxO7A/kjNsqhRJiKkbp3ZMnlraQBS4QgS16A=
#  security:
#    user:
#      name: user@chart.lt
#      password: user
logging:
  level:
    lt:
      codeacademy:
        anestheticChart:
          config: debug
          filter: trace
server:
  error:
    whitelabel:
      enabled: true
---
spring:
  profiles:
    active: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
            schema-locations: classpath:db/db-schema.sql
#            data-locations: classpath:db/initial-data.sql
#      platform: postgresql

#---
#spring:
#  profiles:
#    active: h2
#  datasource:
#    url: jdbc:h2:file:D:/H2
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2
