spring:
  main:
    banner-mode: console
  datasource:
    url: jdbc:h2:mem:anestheticdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath:db/db-schema.sql
      data-locations: classpath:db/initial-data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 3
logging:
  level:
    lt:
      codeacademy:
        anestheticChart:
          config: debug